import * as React from 'react';
import './CreateContract.css';
import "./ContractSearch.module.scss";
import 'bootstrap/dist/css/bootstrap.min.css';
var ContactMainPage = function () {
    return (React.createElement("div", { className: 'contact-section' },
        React.createElement("div", { className: 'cotact-container' },
            React.createElement("div", null,
                React.createElement("div", { className: "card-header d-flex justify-content-between" },
                    React.createElement("div", null,
                        React.createElement("span", { className: 'mx-2' },
                            "Showing ",
                            React.createElement("b", null),
                            " of ",
                            React.createElement("b", null, " "),
                            "Contacts"),
                        React.createElement("input", { type: 'text', className: "main-search" }),
                        React.createElement("button", { className: 'search-button' }, "search")),
                    React.createElement("div", { className: 'table-buttons' },
                        React.createElement("button", null, "Bulk Email"),
                        "\u00A0\u00A0",
                        React.createElement("button", { disabled: true }, "Create Contact"),
                        "\u00A0\u00A0",
                        React.createElement("button", { className: 'btn-light btn-sm mx-1' }, "clear All"),
                        "\u00A0\u00A0",
                        React.createElement("button", { className: 'btn-light btn-sm mx-1' }, "export to excel"),
                        "\u00A0\u00A0",
                        React.createElement("button", { className: 'btn-light btn-sm mx-1' }, "print"),
                        "\u00A0\u00A0",
                        React.createElement("button", { className: 'btn-light btn-sm mx-1' }, "expand"))),
                React.createElement("div", null,
                    React.createElement("table", null,
                        React.createElement("thead", { style: { width: "100%" } },
                            React.createElement("tr", null,
                                React.createElement("th", null,
                                    React.createElement("input", { type: 'checkbox' }),
                                    "All"),
                                React.createElement("th", null,
                                    React.createElement("input", { type: 'text', id: 'Department', className: 'search-input', style: { width: "100px" }, placeholder: 'Staff ID' })),
                                React.createElement("th", null,
                                    React.createElement("input", { type: 'text', id: 'FullName', className: 'search-input', placeholder: 'Name' })),
                                React.createElement("th", null,
                                    React.createElement("input", { type: 'text', id: 'Organization', className: 'search-input', placeholder: 'Organization' })),
                                React.createElement("th", null,
                                    React.createElement("input", { type: 'text', id: 'Position', className: 'search-input', placeholder: 'Job Title' })),
                                React.createElement("th", null,
                                    React.createElement("input", { type: 'text', id: 'Email-Address', className: 'search-input', placeholder: 'Email Address' })),
                                React.createElement("th", null,
                                    React.createElement("input", { type: 'text', id: 'Sites', placeholder: 'city', className: 'search-input' })),
                                React.createElement("th", null))),
                        React.createElement("tbody", null,
                            React.createElement("tr", null,
                                React.createElement("th", { scope: "row" },
                                    React.createElement("input", { type: "checkbox" })),
                                React.createElement("td", null, "vvvvv"),
                                React.createElement("td", { className: 'full-name' },
                                    React.createElement("img", { className: "userImg", src: "https://hhhhteams.sharepoint.com/sites/HHHH/GmBH/SiteCollectionImages/ICONS/32/icon_user.jpg" })),
                                React.createElement("td", { className: "full-name" }, "vvvvv"),
                                React.createElement("td", null, "vvv"),
                                React.createElement("td", null, "vvvv"),
                                React.createElement("td", null, "vvvv"),
                                React.createElement("td", null,
                                    React.createElement("button", { className: 'edit-btn' },
                                        React.createElement("img", { src: 'https://hhhhteams.sharepoint.com/_layouts/images/edititem.gif' }),
                                        " "))))))),
            " ")));
};
export default ContactMainPage;
//# sourceMappingURL=test.js.map